
title: "Jaeyoon Yu"
author: "Jaeyoon Yu"
description: "Central Michigan University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_social: true         # show footer
show_excerpts: false      # show article excerpts on the home page
show_frame: false         # adds a gray frame to the site
show_sidebar: false       # show a sidebar instead of the usual header

# Menu
navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: Home}
  #  - {file:  "CV.md", title: CV}
  - {file: "accounting-news.md", title: AccNews}
  - {file: "account-reference.md", title: AccReference}
  - {file: "Inventory-costing.md", title: InvCosting}
  - {file: "Depreciation.md", title: DepExp}
  - {file: "Benford-analyzer.md", title: BenfordAnalyzer}
  - {file: "Grade-analyzer.md", title: GradeAnalyzer}
  - {file: "python-basics.md", title: PythonBasic}
  - {file: "python-applications.md", title: PythonApplied}
  - {file: "visuals.md", title: Visuals}


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:yu@ese.eur.nl"}
  - {title: Github, icon: github, url: "https://github.com/jaeyoonyu"}

remote_theme: niklasbuschmann/contrast@v2.11

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-gist
